"""面试题库种子数据：3 场景 × 3 难度 × 5 题。"""

SCENARIOS = ("求职面试", "竞赛答辩", "保研复试")
DIFFICULTIES = ("入门", "标准", "压力面")

SEED_QUESTIONS = [
    # 求职面试 / 入门
    {"scenario": "求职面试", "difficulty": "入门", "text": "请做一分钟自我介绍，并说明你为什么适合这个岗位。"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "你了解我们公司的主要业务吗？为什么选择投递这个岗位？"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "请介绍一个你在学校或实习中独立完成的任务。"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "你的职业规划是什么？未来三年你希望达到什么状态？"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "你觉得自己最大的优点是什么？请用一个例子证明。"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "请分享一次你主动学习新技能的经历，你是怎么开始的？"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "你如何看待工作强度或临时加班？你如何保持状态？"},
    {"scenario": "求职面试", "difficulty": "入门", "text": "你实习或兼职中最常被安排的任务是什么？你是如何完成的？"},
    # 求职面试 / 标准
    {"scenario": "求职面试", "difficulty": "标准", "text": "请讲一个你解决复杂问题的经历，你具体采取了哪些行动？"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "当团队意见冲突时，你会如何推动项目继续前进？"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "请介绍一个最能体现你专业能力的项目，并说明结果。"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "如果领导交给你一个从没做过的任务，你会如何快速上手？"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "请举例说明你如何平衡多个任务的优先级。"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "请用 STAR 结构讲一次你成功影响他人的经历。"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "如果需求在交付前突然变更，你会如何调整计划？"},
    {"scenario": "求职面试", "difficulty": "标准", "text": "你如何判断自己适合这个岗位？依据是什么？"},
    # 求职面试 / 压力面
    {"scenario": "求职面试", "difficulty": "压力面", "text": "你刚才的回答里有明显漏洞，你会怎么解释？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "如果入职后发现岗位内容和你预期完全不同，你怎么办？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "你为什么认为自己比同批候选人更值得录用？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "给你三天时间完成一个你从未接触过的项目，你如何安排？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "如果项目临近截止但队友掉链子，你如何保证交付质量？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "如果面试官认为你的项目经历与岗位无关，你会怎么回应？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "你上一次犯过的较大失误是什么？你如何补救？"},
    {"scenario": "求职面试", "difficulty": "压力面", "text": "如果只能保留简历上的一项经历，你保留哪个？为什么？"},
    # 竞赛答辩 / 入门
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "请用一分钟说明你们项目的核心创意和解决什么问题。"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "你们项目的目标用户是谁？为什么他们需要这个产品？"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "你们团队是如何分工的？你主要负责哪部分？"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "你们使用了哪些关键技术？为什么选择它们？"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "项目的开发周期是怎样的？目前完成到什么程度？"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "你们项目最想解决的一个用户痛点是什么？"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "请用一张流程图介绍项目的核心流程。"},
    {"scenario": "竞赛答辩", "difficulty": "入门", "text": "你们如何保证团队进度不落后？"},
    # 竞赛答辩 / 标准
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "你们项目的核心架构是什么？为什么采用这样的分层设计？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "你们如何验证项目效果？用了哪些评测指标？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "相比现有竞品，你们的核心优势是什么？如何证明？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "开发过程中遇到的最大技术难点是什么？如何解决的？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "如果评委质疑你们的创新点，你会如何回应？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "如果评委要求现场演示，你的演示流程是什么？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "你们的数据从哪里来？如何保证数据可信？"},
    {"scenario": "竞赛答辩", "difficulty": "标准", "text": "项目中最难取舍的一个设计决策是什么？"},
    # 竞赛答辩 / 压力面
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "你们项目的用户规模很小，为什么能证明它有价值？"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "如果比赛要求一个月内推翻现有实现，你会保留什么、重做什么？"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "你们项目是否过度依赖某一个第三方服务？出现故障怎么办？"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "请指出你们项目目前最大的缺陷，并说明改进方案。"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "如果评委认为你们的成果只是演示而非产品，你怎么回应？"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "如果只有一周时间重新做这个项目，你会砍掉哪些功能？"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "评委认为你们方案成本过高，你怎么回应？"},
    {"scenario": "竞赛答辩", "difficulty": "压力面", "text": "你们的项目如果去掉 AI 能力还成立吗？"},
    # 保研复试 / 入门
    {"scenario": "保研复试", "difficulty": "入门", "text": "请简单介绍你的学习经历和研究兴趣。"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你为什么选择读研？为什么选择我们学校或专业？"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你本科期间最满意的一门课程是什么？为什么？"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你有没有参与过科研项目或竞赛？简单介绍一下。"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你未来想从事哪个研究方向？目前了解多少？"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你平时如何管理学习和科研时间？"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你本科阶段最有成就感的一件事是什么？"},
    {"scenario": "保研复试", "difficulty": "入门", "text": "你希望研究生阶段获得哪些具体能力？"},
    # 保研复试 / 标准
    {"scenario": "保研复试", "difficulty": "标准", "text": "请详细说明你在某个项目中的具体贡献和收获。"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "你读过哪些与研究方向相关的论文？请介绍其中一篇。"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "如果实验或研究结果与预期不符，你会如何分析？"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "你的研究方法是什么？为什么选择这种方法？"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "你觉得自己目前最大的学术短板是什么？如何补足？"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "请介绍你用过的一个科研工具或实验方法。"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "你如何判断一篇论文是否值得精读？"},
    {"scenario": "保研复试", "difficulty": "标准", "text": "如果研究需要跨学科合作，你会如何推进？"},
    # 保研复试 / 压力面
    {"scenario": "保研复试", "difficulty": "压力面", "text": "你的成绩单里有几门课程并不突出，如何解释？"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "如果导师让你做你不感兴趣的方向，你怎么办？"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "请用五分钟从零讲清你研究领域的一个核心概念。"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "如果你和导师在研究方案上分歧很大，你如何沟通？"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "你能否接受连续三个月没有实验进展？你如何保持动力？"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "如果复试老师指出你基础概念不牢，你会怎么证明自己？"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "你能否接受研究方向与最初设想完全不同？"},
    {"scenario": "保研复试", "difficulty": "压力面", "text": "给你一个陌生领域的一周调研任务，你的计划是什么？"},
]
